// -----------------------------------------------------------------------------
// LG ThinQ Connect Open API client.
//
// This is the only file that talks to LG. It is a thin, dependency-free wrapper
// around the official REST API (Node 20+ `fetch`), mirroring LG's own SDK:
//
//   GET    /devices                    list the appliances of the account
//   GET    /devices/{id}/profile       what the appliance can report/accept
//   GET    /devices/{id}/state         current values
//   POST   /devices/{id}/control       send a command
//
// Authentication is a Personal Access Token (PAT) generated by the user on the
// LG ThinQ developer site and pasted in the Gladys configuration screen. The
// `x-api-key` below is the public service key of the ThinQ Connect program (the
// same value LG ships in its own open-source SDK): it identifies the API, not
// the user, and carries no secret.
// -----------------------------------------------------------------------------

import { randomBytes } from 'node:crypto';
import { createLogger } from '@gladysassistant/integration-sdk';
import { getRegionFromCountry } from './regions.js';
import { ThinqApiError } from './errors.js';

const logger = createLogger({ name: 'thinq-api' });

/** Public service key of the ThinQ Connect program (not a user secret). */
export const THINQ_API_KEY = 'v6GFvkweNo7DK7yD3ylIZ9w52aKBU0eJ7wLXkSR3';

/** Operation phase expected by the API. */
const SERVICE_PHASE = 'OP';

const DEFAULT_TIMEOUT_MS = 15_000;

/**
 * The API rejects a request whose `x-message-id` is not a 22-character
 * base64url blob (a uuid without its padding).
 */
export function generateMessageId() {
  return randomBytes(16).toString('base64url');
}

export class ThinqApi {
  /**
   * @param {object} options
   * @param {string} options.accessToken Personal Access Token
   * @param {string} options.countryCode ISO 3166-1 alpha-2 country of the LG account
   * @param {string} options.clientId stable uuid identifying this client
   * @param {typeof fetch} [options.fetchImpl] injected for tests
   * @param {number} [options.timeoutMs]
   */
  constructor({ accessToken, countryCode, clientId, fetchImpl = fetch, timeoutMs }) {
    this.accessToken = accessToken;
    this.countryCode = String(countryCode).toUpperCase();
    this.clientId = clientId;
    this.region = getRegionFromCountry(this.countryCode);
    this.baseUrl = `https://api-${this.region}.lgthinq.com`;
    this.fetchImpl = fetchImpl;
    this.timeoutMs = timeoutMs ?? DEFAULT_TIMEOUT_MS;
  }

  buildHeaders(extra = {}) {
    return {
      Authorization: `Bearer ${this.accessToken}`,
      'x-country': this.countryCode,
      'x-message-id': generateMessageId(),
      'x-client-id': this.clientId,
      'x-api-key': THINQ_API_KEY,
      'x-service-phase': SERVICE_PHASE,
      ...extra,
    };
  }

  /**
   * Run one API call and unwrap the `response` envelope.
   * @returns {Promise<unknown>} the `response` field of the payload
   */
  async request(method, endpoint, { body, headers } = {}) {
    const url = `${this.baseUrl}/${endpoint}`;
    const requestHeaders = this.buildHeaders({
      ...(body ? { 'Content-Type': 'application/json' } : {}),
      ...headers,
    });

    logger.debug(`${method} ${url}`);

    let httpResponse;
    try {
      httpResponse = await this.fetchImpl(url, {
        method,
        headers: requestHeaders,
        ...(body ? { body: JSON.stringify(body) } : {}),
        signal: AbortSignal.timeout(this.timeoutMs),
      });
    } catch (err) {
      // Network failure / timeout: no ThinQ code to report, keep the cause.
      throw new Error(`LG ThinQ request failed (${method} ${endpoint}): ${err.message}`, {
        cause: err,
      });
    }

    const payload = await httpResponse.json().catch(() => ({}));

    if (!httpResponse.ok) {
      throw new ThinqApiError(
        payload?.error?.code ?? String(httpResponse.status),
        payload?.error?.message ?? httpResponse.statusText,
        httpResponse.status,
      );
    }

    return payload?.response;
  }

  /** Appliances linked to the LG account. */
  async getDevices() {
    const devices = await this.request('GET', 'devices');
    return Array.isArray(devices) ? devices : [];
  }

  /** What an appliance can report and accept (drives the Gladys features). */
  getDeviceProfile(deviceId) {
    return this.request('GET', `devices/${encodeURIComponent(deviceId)}/profile`);
  }

  /** Current values of an appliance. */
  getDeviceState(deviceId) {
    return this.request('GET', `devices/${encodeURIComponent(deviceId)}/state`);
  }

  /**
   * Send a command. The payload mirrors the profile shape, e.g.
   * `{ operation: { airConOperationMode: 'POWER_ON' } }`.
   *
   * `x-conditional-control` lets LG reject a command the appliance cannot
   * honor in its current state instead of silently dropping it.
   */
  controlDevice(deviceId, payload) {
    return this.request('POST', `devices/${encodeURIComponent(deviceId)}/control`, {
      body: payload,
      headers: { 'x-conditional-control': 'true' },
    });
  }
}
